EVENT.GUI.TIMELINE.HOVER
EVENT.GUI.TIMELINE.CLICK
EVENT.GUI.FRAME.CLICK
EVENT.GUI.KMLUPLOADED
EVENT.GUI.PHOTOUPLOADED
EVENT.GUI.NAVIGATETO.FRAME

EVENT.STORY.REFRESH.KML (kml are added/removed to the story)
EVENT.STORY.REFRESH.PHOTO (photos are added/removed to the story)